language: node_js
node_js:
  - 11

dist: trusty
sudo: false
cache: yarn

branches:
  only:
    - release

before_install:
  - openssl aes-256-cbc -K $encrypted_b7e9f3138b36_key -iv $encrypted_b7e9f3138b36_iv -in env.tar.enc -out env.tar -d
  - tar xvf env.tar

before_deploy:
  - npm install netlify-cli -g
  - yarn build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_PUBLISH_KEY -p --dir ./dist
  skip_cleanup: true
  on:
    branch: release


